### ISSUE TITLE
Multithreading needed

### ISSUE THREAD

**Issue by mtyrolski** [kakainet/ImageToLatex#5]
There is need to use multithread system in generating LaTeX dataset. It can improve performance several times.

**Comment by mvxxx** [comment]
[status update]
Implemented multithreading. 
Improved performance:
800 images with size 800 x 800 generated in:
real  0m26,058s
user  3m5,969s
sys  0m1,255s

old performance:

real  1m51,065s
user  1m49,412s
sys  0m1,376s

on 4 threads using intel core i5 8th (in lenovo 320 configuration)

**Comment by mtyrolski** [comment]
[status update]
Implemented multithreading. 
Improved performance:
800 images with size 800 x 800 generated in:
real  0m26,058s
user  3m5,969s
sys  0m1,255s

old performance:

real  1m51,065s
user  1m49,412s
sys  0m1,376s

on 4 threads using intel core i5 8th (in lenovo 320 configuration).
Waiting for @kubachrabanski approval.
